[font]
size = 14.0

[font.normal]
family = "JetbrainsMonoNerdFont"
style = "Regular"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[general]
import = [
    "~/.config/alacritty/themes/themes/moonfly.toml"
]

[colors.primary]
background = "#000000"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

